name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Configure MCP server with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected outcome...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually occurred...
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      options:
        - Claude Code
        - VS Code (Continue)
        - Cursor
        - Other
    validations:
      required: true

  - type: dropdown
    id: adapter
    attributes:
      label: Storage Adapter
      description: Which storage adapter are you using?
      options:
        - Local (file-based)
        - Redis
        - Custom
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: Which version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Paste relevant error messages or logs
      placeholder: Paste error messages or logs here...
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (screenshots, configuration files, etc.)
      placeholder: Add any additional context here...
