[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "claude-session-coordinator"
version = "0.1.0"
description = "MCP server for coordinating multiple Claude AI sessions"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "BANCS AS", email = "contact@bancs.no"}
]
keywords = ["claude", "mcp", "coordination", "ai", "assistant"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "mcp>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]
redis = [
    "redis>=5.0.0",
]

[project.scripts]
claude-session-coordinator = "claude_session_coordinator.__main__:cli_main"

[project.urls]
Homepage = "https://github.com/BANCS-Norway/claude_session_coordinator"
Documentation = "https://csc.bancs.no"
Repository = "https://github.com/BANCS-Norway/claude_session_coordinator"
Issues = "https://github.com/BANCS-Norway/claude_session_coordinator/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/claude_session_coordinator"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=src/claude_session_coordinator --cov-report=html --cov-report=term-missing"

[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
